version: '3.8'

services:
  emtk-www:
    build: .
    container_name: emtk-www
    ports:
      - "8080:80" # Maps port 8080 of the host to port 80 of the container
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
